/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package koinoxristaapplicatio;

import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author BILL
 */
public class EkdosiApodeiksis extends javax.swing.JFrame {

    /**
     * Creates new form EkdosiApodeiksis
     */
    public EkdosiApodeiksis() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        asdasd = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ConfirmBtn = new javax.swing.JButton();
        VerifyConn = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        KodDiamer = new javax.swing.JTextField();
        OnomaEnoikou = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ApodeiksiField = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        KodPol = new javax.swing.JTextField();
        firstFloorCheck = new javax.swing.JCheckBox();
        jLabel23 = new javax.swing.JLabel();
        MonthYear2 = new javax.swing.JTextField();
        PrintBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Quit = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 204, 51));

        asdasd.setBackground(new java.awt.Color(102, 102, 102));
        asdasd.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        asdasd.setText("ΌΝΟΜΑ ΕΝΟΙΚΟΥ:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel3.setText("ΕΚΔΟΣΗ ΑΠΟΔΕΙΞΗΣ ΠΛΗΡΩΜΗΣ ΔΙΑΜΕΡΙΣΜΑΤΟΣ");

        ConfirmBtn.setBackground(new java.awt.Color(0, 0, 153));
        ConfirmBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ConfirmBtn.setForeground(new java.awt.Color(255, 204, 51));
        ConfirmBtn.setText("ΔΗΜΙΟΥΡΓΙΑ ΑΠΟΔΕΙΞΗΣ");
        ConfirmBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        ConfirmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmBtnActionPerformed(evt);
            }
        });

        VerifyConn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        jLabel2.setText("ΚΩΔ.ΔΙΑΜΕΡΙΣΜΑΤΟΣ:");

        KodDiamer.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        KodDiamer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        OnomaEnoikou.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        OnomaEnoikou.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        ApodeiksiField.setColumns(20);
        ApodeiksiField.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        ApodeiksiField.setRows(5);
        jScrollPane1.setViewportView(ApodeiksiField);

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        jLabel4.setText("ΚΩΔ.ΠΟΛΥΚΑΤΟΙΚΙΑΣ:");

        KodPol.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        KodPol.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        firstFloorCheck.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        firstFloorCheck.setText("Πρώτος όροφος");
        firstFloorCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstFloorCheckActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        jLabel23.setText("ΗΜΕΡΟΜΗΝΙΑ ΕΞΟΔΩΝ:");

        MonthYear2.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        MonthYear2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        PrintBtn.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        PrintBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\BILL\\Desktop\\FOLDERS\\icons8-print-filled-23.png")); // NOI18N
        PrintBtn.setText("Εκτύπωση απόδειξης");
        PrintBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(firstFloorCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(asdasd)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel23))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(OnomaEnoikou, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(KodPol, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                                    .addComponent(MonthYear2)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ConfirmBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(KodDiamer, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 2, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(VerifyConn, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(PrintBtn)))
                .addGap(8, 8, 8))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PrintBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addComponent(VerifyConn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(55, 55, 55)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(MonthYear2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel23))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(asdasd, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(OnomaEnoikou, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(KodPol, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(KodDiamer, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(firstFloorCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ConfirmBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(87, 87, 87))
        );

        jPanel1.setBackground(new java.awt.Color(0, 0, 153));
        jPanel1.setForeground(new java.awt.Color(0, 0, 51));

        jLabel1.setBackground(new java.awt.Color(255, 204, 51));
        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 31)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 0));
        jLabel1.setText("       ΕΦΑΡΜΟΓΗ ΥΠΟΛΟΓΙΣΜΟΥ ΚΟΙΝΟΧΡΗΣΤΩΝ");

        Quit.setIcon(new javax.swing.ImageIcon("C:\\Users\\BILL\\Desktop\\if_exit_3226.png")); // NOI18N
        Quit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                QuitMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 819, Short.MAX_VALUE)
                .addGap(233, 233, 233)
                .addComponent(Quit))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Quit)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jMenu1.setText("Επιλογές");
        jMenu1.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jMenu1.setPreferredSize(new java.awt.Dimension(73, 33));

        jMenuItem4.setText("Eισαγωγή Πολυκατοικίας");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem5.setText("Εισαγωγή Διαμερίσματος");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuItem6.setText("Υπολογισμός εξόδων πολυκατοικίας");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuItem7.setText("Έκδοση Απόδειξης");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem7);

        jMenuItem8.setText("Εμφάνιση Διαμερισμάτων");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem8);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ConfirmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmBtnActionPerformed

        String query = "SELECT  Orofos,Tmetra FROM diamerisma WHERE OwnerName=? AND KodDiamer=?";
        String query1 = "SELECT MonthYear, Koinoxrista,Thermansi,Sunidioktisia,Anelk FROM eksodaPolukatoikias WHERE KodPol=? AND MonthYear=?";
        String query2 = "SELECT TM,NAME FROM polukatoikia WHERE KodPol=?";

        PreparedStatement st, st1, st2;
        Connection conn;

        try {
            String e1 = OnomaEnoikou.getText();
            String e2 = (KodDiamer.getText());
            int e3 = Integer.parseInt(KodPol.getText());
            String e4=MonthYear2.getText();
            
            String url = "jdbc:sqlite:C:/Users/Bill/Desktop/polukatoikiadb.db";
            conn = DriverManager.getConnection(url);
            st = conn.prepareStatement(query);
            st1 = conn.prepareStatement(query1);
            st2 = conn.prepareStatement(query2);

            st.setString(1, e1);
            st.setString(2, e2);
            st1.setInt(1, e3);
            st2.setInt(1, e3);
            st1.setString(2,e4);
            

            ResultSet rs = st.executeQuery();
            ResultSet rs2 = st1.executeQuery();
            ResultSet rs3 = st2.executeQuery();

            if (rs.next()) {

                int orofos = rs.getInt(1);
                double tetragwnikaMetra = rs.getDouble(2);
                if (rs3.next()) {
                    String Diaxeirisths=rs3.getString(2);
                    double TMPolukatoikias = rs3.getDouble(1);
                    if (rs2.next()) {
                        
                        String monthYear = rs2.getString(1);
                        double koin = rs2.getDouble(2);
                        double ther = rs2.getDouble(3);
                        double Sunidioktisia=rs2.getDouble(4);
                        double Anelk=rs2.getDouble(5);
                        
                        
                        System.out.println(koin);
                        System.out.println(ther);
                        System.out.println(Sunidioktisia);
                        System.out.println(Anelk);
                        System.out.println(TMPolukatoikias);
                        System.out.println(tetragwnikaMetra);
                        double xiliosta = tetragwnikaMetra / TMPolukatoikias *0.1000;
                        koin = koin  * xiliosta;
                        ther = ther * xiliosta;
                        System.out.println(koin);
                        System.out.println(ther);
                       
                        boolean check = firstFloorCheck.isSelected();
                        if (check == false) {
                            Anelk=Anelk*xiliosta;
                        } else {
                            Anelk=Anelk*0;
                        }
                        double sunolo=koin+ther+Anelk;
                        JOptionPane.showMessageDialog(null, "ΕΠΙΤΥΧΗΣ ΔΗΜΙΟΥΡΓΙΑ ΑΠΟΔΕΙΞΗΣ!");
                        ApodeiksiField.setText("-------------------------- ΑΠΟΔΕΙΞΗ ΠΛΗΡΩΜΗΣ ΚΟΙΝΟΧΡΗΣΤΩΝ----------------\n\n" + ""
                                + "Ο/H ΚΥΡΙOΣ/A " + e1 + "\n"
                                + " ΤΟΥ ΔΙΑΜΕΡΙΣΜΑΤΟΣ " + e2 + " ΤΟΥ ΟΡΟΦΟΥ " + orofos
                                + "\n\n ΜΕ ΤΕΤΡΑΓΩΝΙΚΑ ΜΕΤΡΑ " + tetragwnikaMetra + "\n\n" + " ΠΛΗΡΩΣΕ ΑΝΑΛΥΤΙΚΑ: \n\n"
                                + " ΚΟΙΝΟΧΡΗΣΤΑ: " + Math.round(koin) + "  € | "+ "   | " + "  ΘΕΡΜΑΝΣΗ: " + Math.round(ther) + "  €  |" + " ΧΡΕΩΣΗ ΑΝΕΛΚΥΣΤΗΡΑ: "
                        + Math.round(Anelk) +"  € "+ "\n\n ΣΥΝΟΛΟ: "  + Math.round(sunolo)+" €"
                        + "\n\n ΜΕ ΕΚΤΙΜΗΣΗ Ο ΔΙΑΧΕΙΡΙΣΤΗΣ \n\n" + Diaxeirisths);
                    }
                }
               
            } else {
                JOptionPane.showMessageDialog(null, "ΔΕΝ ΒΡΕΘΗΚΑΝ ΤΑ ΣΤΟΧΕΙΑ ΠΟΥ ΕΙΣΑΓΑΤΕ!", "Error", JOptionPane.ERROR_MESSAGE);

            }

        } catch (Exception e) {
            e.printStackTrace();

        }
        
        //
    }//GEN-LAST:event_ConfirmBtnActionPerformed

    private void firstFloorCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstFloorCheckActionPerformed
        // TODO add your handling code here:
    
    }//GEN-LAST:event_firstFloorCheckActionPerformed

    private void PrintBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintBtnActionPerformed
        String ektiposi = ApodeiksiField.getText();    //step1: get the content of the textfield
        String Onoma= JOptionPane.showInputDialog("ΠΑΡΑΚΑΛΩ ΔΩΣΤΕ ΤΟ ΟΝΟΜΑ ΠΟΥ ΘΑ ΕΧΕΙ ΤΟ ΔΗΜΙΟΥΡΓΗΜΕΝΟ ΑΡΧΕΙΟ");
        
        
    try {

                File file = new File("/C:/Users/Bill/Desktop/"+Onoma);

                
                if (!file.exists()) {
                    file.createNewFile();
                }

                FileWriter fw = new FileWriter(file.getAbsoluteFile());
                BufferedWriter bw = new BufferedWriter(fw);
                bw.write(ektiposi);    
                bw.close();
                JOptionPane.showMessageDialog(null, "ΕΠΙΤΥΧΗΣ ΕΚΤΥΠΩΣΗ ΑΠΟΔΕΙΞΗΣ ΜΕ ΟΝΟΜΑ: "+ Onoma);

            } catch (IOException e) {
                e.printStackTrace();
}

   
    }//GEN-LAST:event_PrintBtnActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        EisagogiPolukatoikias eisPol=new EisagogiPolukatoikias();
        eisPol.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        EisagogiDiamerismatos eisDiamer=new EisagogiDiamerismatos();
        eisDiamer.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        EisagogiEksodwnPol eiseksodwn=new EisagogiEksodwnPol();
        eiseksodwn.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
         JOptionPane.showMessageDialog(null, "ΕΙΣΤΕ ΗΔΗ ΣΕ ΑΥΤΗ ΤΗΝ ΣΕΛΙΔΑ!");
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void QuitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QuitMouseClicked
        // TODO
        int result= JOptionPane.showConfirmDialog(null,
            "ΕΙΣΤΕ ΣΙΓΟΥΡΟΙ ΟΤΙ θΕΛΕΤΕ ΝΑ ΚΑΝΕΤΕ ΕΞΟΔΟ ΑΠΟ ΤΟ ΣΥΣΤΗΜΑ;",
            "ΕΞΟΔΟΣ", JOptionPane.YES_NO_CANCEL_OPTION);
        if (result == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_QuitMouseClicked

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        EmfanisiDiamerismatwn emfDiamer=new EmfanisiDiamerismatwn();
        emfDiamer.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EkdosiApodeiksis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EkdosiApodeiksis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EkdosiApodeiksis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EkdosiApodeiksis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EkdosiApodeiksis().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea ApodeiksiField;
    private javax.swing.JButton ConfirmBtn;
    private javax.swing.JTextField KodDiamer;
    private javax.swing.JTextField KodPol;
    private javax.swing.JTextField MonthYear2;
    private javax.swing.JTextField OnomaEnoikou;
    private javax.swing.JButton PrintBtn;
    private javax.swing.JLabel Quit;
    private javax.swing.JLabel VerifyConn;
    private javax.swing.JLabel asdasd;
    private javax.swing.JCheckBox firstFloorCheck;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
