/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package koinoxristaapplicatio;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;

import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author BILL
 */
public class EisagogiDiamerismatos extends javax.swing.JFrame {
    public boolean Filled=false;

    /**
     * Creates new form EisagogiDiamerismatos
     */
    public EisagogiDiamerismatos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Quit = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Submit2Btn = new javax.swing.JButton();
        VerifyConn = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        KodPol = new javax.swing.JTextField();
        Orofos = new javax.swing.JTextField();
        KodDiamer = new javax.swing.JTextField();
        OwnerName = new javax.swing.JTextField();
        TM = new javax.swing.JTextField();
        OwnerTel = new javax.swing.JTextField();
        Continue2Btn = new javax.swing.JButton();
        Clear3btn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        Quit1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();

        Quit.setIcon(new javax.swing.ImageIcon("C:\\Users\\BILL\\Desktop\\if_exit_3226.png")); // NOI18N
        Quit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                QuitMouseClicked(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 204, 51));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("ΚΑΤΑΧΩΡΗΣΗ ΝΕΟΥ ΔΙΑΜΕΡΙΣΜΑΤΟΣ");

        Submit2Btn.setBackground(new java.awt.Color(0, 0, 153));
        Submit2Btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Submit2Btn.setForeground(new java.awt.Color(255, 204, 51));
        Submit2Btn.setText("ΚΑΤΑΧΩΡΗΣΗ ");
        Submit2Btn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        Submit2Btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Submit2BtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Submit2BtnMouseExited(evt);
            }
        });
        Submit2Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Submit2BtnActionPerformed(evt);
            }
        });

        VerifyConn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel4.setText("ΚΩΔ. ΠΟΛΥΚΑΤΟΙΚΙΑΣ:");

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel1.setText("ΟΡΟΦΟΣ:");

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel2.setText("ΚΩΔ. ΔΙΑΜΕΡΙΣΜΑΤΟΣ:");

        jLabel5.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel5.setText("ΟΝΟΜΑΤΕΠΩΝΥΜΟ ΙΔΙΟΚΤΗΤΗ:");

        jLabel6.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel6.setText("ΤΕΤΡΑΓΩΝΙΚΑ ΜΕΤΡΑ (ΤΜ):");

        jLabel7.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel7.setText("ΤΗΛ.ΙΔΙΟΚΤΗΤΗ");

        KodPol.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        KodPol.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        Orofos.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        Orofos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        Orofos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrofosActionPerformed(evt);
            }
        });

        KodDiamer.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        KodDiamer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        OwnerName.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        OwnerName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        TM.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        TM.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        OwnerTel.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        OwnerTel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        Continue2Btn.setBackground(new java.awt.Color(0, 0, 153));
        Continue2Btn.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        Continue2Btn.setForeground(new java.awt.Color(255, 204, 51));
        Continue2Btn.setText("ΣΥΝΕΧΕΙΑ ");
        Continue2Btn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        Continue2Btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Continue2BtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Continue2BtnMouseExited(evt);
            }
        });
        Continue2Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Continue2BtnActionPerformed(evt);
            }
        });

        Clear3btn.setBackground(new java.awt.Color(0, 0, 153));
        Clear3btn.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        Clear3btn.setForeground(new java.awt.Color(255, 204, 51));
        Clear3btn.setText("ΚΑΘΑΡΙΣΜΟΣ ΦΟΡΜΑΣ");
        Clear3btn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        Clear3btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Clear3btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Clear3btnMouseExited(evt);
            }
        });
        Clear3btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Clear3btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(Submit2Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Clear3btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Continue2Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(57, 57, 57)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))))
                                .addGap(6, 6, 6)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(OwnerTel, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(OwnerName, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                                        .addComponent(TM)
                                        .addComponent(KodDiamer)
                                        .addComponent(Orofos)
                                        .addComponent(KodPol)))))
                        .addGap(70, 70, 70)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(113, 113, 113)
                        .addComponent(VerifyConn, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(VerifyConn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(Orofos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(KodDiamer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(OwnerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(TM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(OwnerTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(KodPol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(72, 72, 72)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Submit2Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Continue2Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Clear3btn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(122, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(0, 0, 153));
        jPanel1.setForeground(new java.awt.Color(0, 0, 51));

        jLabel12.setBackground(new java.awt.Color(255, 204, 51));
        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 31)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 0));
        jLabel12.setText("       ΕΦΑΡΜΟΓΗ ΥΠΟΛΟΓΙΣΜΟΥ ΚΟΙΝΟΧΡΗΣΤΩΝ");

        Quit1.setIcon(new javax.swing.ImageIcon("C:\\Users\\BILL\\Desktop\\if_exit_3226.png")); // NOI18N
        Quit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Quit1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(75, 75, 75))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Quit1))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Quit1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jMenuBar1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jMenuBar1.setPreferredSize(new java.awt.Dimension(73, 33));

        jMenu1.setText("Επιλογές");
        jMenu1.setFocusable(false);
        jMenu1.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N

        jMenuItem1.setText("Eισαγωγή Πολυκατοικίας");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Εισαγωγή Διαμερίσματος");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Υπολογισμός εξόδων πολυκατοικίας");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("Έκδοση Απόδειξης");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem7.setText("Εμφάνιση Διαμερισμάτων");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem7);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void QuitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QuitMouseClicked
        // TODO
        int result= JOptionPane.showConfirmDialog(null,
            "ΕΙΣΤΕ ΣΙΓΟΥΡΟΙ ΟΤΙ θΕΛΕΤΕ ΝΑ ΚΑΝΕΤΕ ΕΞΟΔΟ ΑΠΟ ΤΟ ΣΥΣΤΗΜΑ;",
            "ΕΞΟΔΟΣ", JOptionPane.YES_NO_CANCEL_OPTION);
        if (result == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_QuitMouseClicked

    private void Quit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Quit1MouseClicked
        int result= JOptionPane.showConfirmDialog(null,
            "ΕΙΣΤΕ ΣΙΓΟΥΡΟΙ ΟΤΙ θΕΛΕΤΕ ΝΑ ΚΑΝΕΤΕ ΕΞΟΔΟ ΑΠΟ ΤΟ ΣΥΣΤΗΜΑ;",
            "ΕΞΟΔΟΣ", JOptionPane.YES_NO_CANCEL_OPTION);
        if (result == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_Quit1MouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        EisagogiPolukatoikias eisPol=new EisagogiPolukatoikias();
        eisPol.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
         JOptionPane.showMessageDialog(null, "ΕΙΣΤΕ ΗΔΗ ΣΕ ΑΥΤΗ ΤΗΝ ΣΕΛΙΔΑ!");
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        EisagogiEksodwnPol eisEksodwn=new EisagogiEksodwnPol();
        eisEksodwn.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        EkdosiApodeiksis ekdApo=new EkdosiApodeiksis();
        ekdApo.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void Clear3btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Clear3btnActionPerformed
        KodPol.setText("");
        Orofos.setText("");
        KodDiamer.setText("");
        OwnerName.setText("");
        TM.setText("");
        OwnerTel.setText("");

    }//GEN-LAST:event_Clear3btnActionPerformed

    private void Clear3btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Clear3btnMouseExited
        Clear3btn.setBackground(new java.awt.Color(0, 0, 153));
    }//GEN-LAST:event_Clear3btnMouseExited

    private void Clear3btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Clear3btnMouseEntered
        Clear3btn.setBackground(new java.awt.Color(0, 0, 51));
    }//GEN-LAST:event_Clear3btnMouseEntered

    private void Continue2BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Continue2BtnActionPerformed

        EisagogiEksodwnPol eis2 = new EisagogiEksodwnPol();
        eis2.setVisible(true);
    }//GEN-LAST:event_Continue2BtnActionPerformed

    private void Continue2BtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Continue2BtnMouseExited
        Continue2Btn.setBackground(new java.awt.Color(0, 0, 153));
    }//GEN-LAST:event_Continue2BtnMouseExited

    private void Continue2BtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Continue2BtnMouseEntered
        Continue2Btn.setBackground(new java.awt.Color(0, 0, 51));
    }//GEN-LAST:event_Continue2BtnMouseEntered

    private void OrofosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrofosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OrofosActionPerformed

    private void Submit2BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Submit2BtnActionPerformed
        PreparedStatement st;
        Connection conn;
        String url = "jdbc:sqlite:C:/Users/BILL/Desktop/polukatoikiadb.db";
        String sql = "INSERT INTO diamerisma(KodPol,Orofos,KodDiamer,TMetra,OwnerName,OwnerTel) VALUES(?,?,?,?,?,?)";

        try {

            conn = (Connection) DriverManager.getConnection(url);
            st = conn.prepareStatement(sql);
            st.setString(1, KodPol.getText());
            st.setString(2, Orofos.getText());
            st.setString(3,KodDiamer.getText());
            st.setString(4, TM.getText());
            st.setString(5, OwnerName.getText());
            st.setString(6, OwnerTel.getText());

            st.executeUpdate();

            JOptionPane.showMessageDialog(null, "ΕΠΙΤΥΧΗΣ ΚΑΤΑΧΩΡΗΣΗ!");
            

        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "AΠΟΤΥΧΗΜΕΝΗ ΚΑΤΑΧΩΡΗΣΗ", "Error", JOptionPane.ERROR_MESSAGE);

        }
        

        //
    }//GEN-LAST:event_Submit2BtnActionPerformed

    private void Submit2BtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Submit2BtnMouseExited
        Submit2Btn.setBackground(new java.awt.Color(0, 0, 153));        // TODO add your handling code here:
    }//GEN-LAST:event_Submit2BtnMouseExited

    private void Submit2BtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Submit2BtnMouseEntered
        Submit2Btn.setBackground(new java.awt.Color(0, 0, 51));
    }//GEN-LAST:event_Submit2BtnMouseEntered

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        EmfanisiDiamerismatwn emfDiamer=new EmfanisiDiamerismatwn();
        emfDiamer.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem7ActionPerformed
 
     
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EisagogiDiamerismatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EisagogiDiamerismatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EisagogiDiamerismatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EisagogiDiamerismatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EisagogiDiamerismatos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Clear3btn;
    private javax.swing.JButton Continue2Btn;
    private javax.swing.JTextField KodDiamer;
    private javax.swing.JTextField KodPol;
    private javax.swing.JTextField Orofos;
    private javax.swing.JTextField OwnerName;
    private javax.swing.JTextField OwnerTel;
    private javax.swing.JLabel Quit;
    private javax.swing.JLabel Quit1;
    private javax.swing.JButton Submit2Btn;
    private javax.swing.JTextField TM;
    private javax.swing.JLabel VerifyConn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
