/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package koinoxristaapplicatio;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author BILL
 */
public class EisagogiEksodwnPol extends javax.swing.JFrame {

    public boolean Fiiled = false;

    /**
     * Creates new form EisagogiEksodwnPol
     */
    public EisagogiEksodwnPol() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPanel2 = new javax.swing.JPanel();
        asdasd = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        VerifyConn = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Revma = new javax.swing.JTextField();
        Nero = new javax.swing.JTextField();
        Katharistria = new javax.swing.JTextField();
        DiafEksoda = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        AksiaTherm = new javax.swing.JTextField();
        SintKafstira = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Xaratsi = new javax.swing.JTextField();
        EksodaPortas = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        Suntirisi = new javax.swing.JTextField();
        EksodaAnt = new javax.swing.JTextField();
        EksodaTexnikwn = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        SunoloKoin = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        SunoloTher = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        SunoloSunidioktisia = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        SunoloAnelk = new javax.swing.JTextField();
        CalculateEksoda = new javax.swing.JButton();
        ClearBtn = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        KodPol = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        MonthYear = new javax.swing.JTextField();
        Submit4Btn = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        Sunolo = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        FusikoAerio = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Quit1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 204, 51));

        asdasd.setBackground(new java.awt.Color(102, 102, 102));
        asdasd.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        asdasd.setForeground(new java.awt.Color(0, 0, 153));
        asdasd.setText("ΚΟΙΝΟΧΡΗΣΤΑ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("ΠΑΡΑΚΑΛΟΥΜΕ ΕΙΣΑΓΕΤΕ ΤΑ ΕΞΟΔΑ ΠΟΛΥΚΑΤΟΙΚΙΑΣ");

        VerifyConn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        jLabel4.setText("ΡΕΥΜΑ:");

        jLabel5.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        jLabel5.setText("ΝΕΡΟ:");

        jLabel6.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        jLabel6.setText("ΚΑΘΑΡΙΣΤΡΙΑ:");

        jLabel7.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        jLabel7.setText("ΔΙΑΦ. ΕΞΟΔΑ:");

        Revma.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        Revma.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        Nero.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        Nero.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        Katharistria.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        Katharistria.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        DiafEksoda.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        DiafEksoda.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 153));
        jLabel2.setText("ΘΕΡΜΑΝΣΗ");

        jLabel8.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        jLabel8.setText("ΑΞΙΑ ΘΕΡΜΑΝΣΗΣ:");

        jLabel9.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        jLabel9.setText("ΣΥΝΤ. ΚΑΥΣΤΗΡΑ:");

        AksiaTherm.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        AksiaTherm.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        AksiaTherm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AksiaThermActionPerformed(evt);
            }
        });

        SintKafstira.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        SintKafstira.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel10.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 153));
        jLabel10.setText("ΣΥΝΙΔΙΟΚΤΗΣΙΑ");

        jLabel11.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        jLabel11.setText("ΕΕΤΗΔΕ:");

        jLabel12.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        jLabel12.setText("ΕΞΟΔΑ ΠΟΡΤΑΣ:");

        Xaratsi.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        Xaratsi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        EksodaPortas.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        EksodaPortas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel14.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 153));
        jLabel14.setText(" ΑΝΕΛΚΥΣΤΗΡΑΣ");

        jLabel15.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        jLabel15.setText("ΣΥΝΤΗΡΗΣΗ ΑΝΕΛΚ.:");

        jLabel16.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        jLabel16.setText(" ΕΞΟΔΑ ΑΝΤΑΛΛΑΚΤΙΚΩΝ:");

        jLabel17.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        jLabel17.setText("ΕΞΟΔΑ ΤΕΧΝΙΚΩΝ:");

        Suntirisi.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        Suntirisi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        Suntirisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SuntirisiActionPerformed(evt);
            }
        });

        EksodaAnt.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        EksodaAnt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        EksodaTexnikwn.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        EksodaTexnikwn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel18.setFont(new java.awt.Font("sansserif", 1, 25)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 153));
        jLabel18.setText("ΣΥΝΟΛΟ ΚΟΙΝΟΧΡΗΣΤΩΝ:");

        SunoloKoin.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        SunoloKoin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel19.setFont(new java.awt.Font("sansserif", 1, 25)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 153));
        jLabel19.setText("ΣΥΝΟΛΟ ΘΕΡΜΑΝΣΗΣ:");

        SunoloTher.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        SunoloTher.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        SunoloTher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SunoloTherActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("sansserif", 1, 25)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 153));
        jLabel20.setText("ΣΥΝΟΛΟ ΣΥΝΙΔΙΟΚΤΗΣΙΑΣ:");

        SunoloSunidioktisia.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        SunoloSunidioktisia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        SunoloSunidioktisia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SunoloSunidioktisiaActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("sansserif", 1, 25)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 153));
        jLabel21.setText("ΣΥΝΟΛΟ ΑΝΕΛΚΥΣΤΗΡΑ:");

        SunoloAnelk.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        SunoloAnelk.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        CalculateEksoda.setBackground(new java.awt.Color(0, 0, 153));
        CalculateEksoda.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        CalculateEksoda.setForeground(new java.awt.Color(255, 204, 51));
        CalculateEksoda.setText("ΥΠΟΛΟΓΙΣΜΟΣ ΕΞΟΔΩΝ");
        CalculateEksoda.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        CalculateEksoda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CalculateEksodaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CalculateEksodaMouseExited(evt);
            }
        });
        CalculateEksoda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculateEksodaActionPerformed(evt);
            }
        });

        ClearBtn.setBackground(new java.awt.Color(0, 0, 153));
        ClearBtn.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        ClearBtn.setForeground(new java.awt.Color(255, 204, 51));
        ClearBtn.setText("ΚΑΘΑΡΙΣΜΟΣ ΦΟΡΜΑΣ");
        ClearBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        ClearBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ClearBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ClearBtnMouseExited(evt);
            }
        });
        ClearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearBtnActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel22.setText("ΚΩΔΙΚΟΣ ΠΟΛΥΚΑΤΟΙΚΙΑΣ:");

        KodPol.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        KodPol.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        KodPol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KodPolActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel23.setText("ΗΜΕΡΟΜΗΝΙΑ ΕΞΟΔΩΝ (ΜΗΝΑΣ/ΕΤΟΣ):");

        MonthYear.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        MonthYear.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        Submit4Btn.setBackground(new java.awt.Color(0, 0, 153));
        Submit4Btn.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        Submit4Btn.setForeground(new java.awt.Color(255, 204, 51));
        Submit4Btn.setText("ΚΑΤΑΧΩΡΗΣΗ");
        Submit4Btn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        Submit4Btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Submit4BtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Submit4BtnMouseExited(evt);
            }
        });
        Submit4Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Submit4BtnActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("sansserif", 1, 28)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 153));
        jLabel24.setText("ΣΥΝΟΛΟ");

        Sunolo.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        Sunolo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        Sunolo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SunoloActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        jLabel25.setText("ΦΥΣΙΚΟ ΑΕΡΙΟ:");

        FusikoAerio.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        FusikoAerio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(asdasd, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel6))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel7)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(DiafEksoda)
                                    .addComponent(Revma)
                                    .addComponent(Nero)
                                    .addComponent(Katharistria, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE))))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(AksiaTherm, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(57, 57, 57)
                                        .addComponent(jLabel2))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel25)
                                            .addComponent(jLabel9))
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(SintKafstira, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addGap(12, 12, 12)
                                                .addComponent(FusikoAerio, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(60, 60, 60)
                                .addComponent(jLabel10))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel23))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel14)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(KodPol, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel17))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(Xaratsi, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel15))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(EksodaPortas, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel16))))
                                    .addComponent(CalculateEksoda, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(MonthYear, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Submit4Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ClearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(286, 286, 286)
                                .addComponent(jLabel13))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EksodaAnt, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Suntirisi, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EksodaTexnikwn, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addComponent(VerifyConn, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SunoloKoin, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21)
                            .addComponent(jLabel24))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(SunoloTher)
                            .addComponent(SunoloSunidioktisia)
                            .addComponent(SunoloAnelk, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                            .addComponent(Sunolo))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(Revma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8)
                                .addComponent(AksiaTherm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Suntirisi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel10)
                            .addComponent(jLabel13)
                            .addComponent(asdasd)
                            .addComponent(jLabel14))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(VerifyConn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(Xaratsi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15))))
                        .addGap(0, 6, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EksodaAnt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EksodaTexnikwn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel12)
                                .addComponent(EksodaPortas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(SintKafstira, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9)
                                    .addComponent(Nero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(Katharistria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(DiafEksoda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel25)
                                    .addComponent(FusikoAerio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel22)
                                    .addComponent(KodPol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel23)
                                    .addComponent(MonthYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SunoloKoin, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(SunoloTher, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel20)
                            .addComponent(SunoloSunidioktisia, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(SunoloAnelk, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Sunolo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(CalculateEksoda, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ClearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Submit4Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        SunoloKoin.getAccessibleContext().setAccessibleDescription("");

        jPanel1.setBackground(new java.awt.Color(0, 0, 153));
        jPanel1.setForeground(new java.awt.Color(0, 0, 51));

        jLabel1.setBackground(new java.awt.Color(255, 204, 51));
        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 31)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 0));
        jLabel1.setText("       ΕΦΑΡΜΟΓΗ ΥΠΟΛΟΓΙΣΜΟΥ ΚΟΙΝΟΧΡΗΣΤΩΝ");

        Quit1.setIcon(new javax.swing.ImageIcon("C:\\Users\\BILL\\Desktop\\if_exit_3226.png")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(287, 287, 287)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1065, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Quit1)
                .addGap(92, 92, 92))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Quit1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jMenuBar1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N

        jMenu1.setText("Επιλογές");
        jMenu1.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jMenu1.setPreferredSize(new java.awt.Dimension(73, 33));

        jMenuItem1.setText("Eισαγωγή Πολυκατοικίας");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Εισαγωγή Διαμερίσματος");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Υπολογισμός εξόδων πολυκατοικίας");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("Έκδοση Απόδειξης");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem5.setText("Εμφάνιση Διαμερισμάτων");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AksiaThermActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AksiaThermActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AksiaThermActionPerformed

    private void SuntirisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SuntirisiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SuntirisiActionPerformed

    private void SunoloTherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SunoloTherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SunoloTherActionPerformed

    private void CalculateEksodaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculateEksodaActionPerformed
        double revma = Double.parseDouble(Revma.getText());
        double nero = Double.parseDouble(Nero.getText());
        double katharistria = Double.parseDouble(Katharistria.getText());
        double diafEksoda = Double.parseDouble(DiafEksoda.getText());

        double fusikoAerio=Double.parseDouble(FusikoAerio.getText());
        double aksiathermansis = Double.parseDouble(AksiaTherm.getText());
        double sintkafstira = Double.parseDouble(SintKafstira.getText());

        double xaratsi = Double.parseDouble(Xaratsi.getText());
        double eksodaportas = Double.parseDouble(EksodaPortas.getText());

        double suntirisi = Double.parseDouble(Suntirisi.getText());
        double eksodaant = Double.parseDouble(EksodaAnt.getText());
        double eksodatexn = Double.parseDouble(EksodaTexnikwn.getText());

        SunoloKoin.setText("" + (revma + nero + katharistria + diafEksoda ) + " €");
        SunoloTher.setText("" + (aksiathermansis + sintkafstira) + " €");
        SunoloSunidioktisia.setText("" + (eksodaportas + xaratsi) + " €");
        SunoloAnelk.setText("" + (suntirisi + eksodaant + eksodatexn) + " €");

        Sunolo.setText("" + (revma + nero + katharistria + diafEksoda + aksiathermansis + sintkafstira +fusikoAerio+ eksodaportas + xaratsi + suntirisi + eksodaant + eksodatexn) + "  €");

        //
    }//GEN-LAST:event_CalculateEksodaActionPerformed

    private void ClearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearBtnActionPerformed
        Revma.setText("");
        Nero.setText("");
        Katharistria.setText("");
        DiafEksoda.setText("");
        AksiaTherm.setText("");
        SintKafstira.setText("");
        Xaratsi.setText("");
        EksodaPortas.setText("");
        Suntirisi.setText("");
        EksodaTexnikwn.setText("");
        EksodaAnt.setText("");
        SunoloKoin.setText("");
        SunoloTher.setText("");
        SunoloSunidioktisia.setText("");
        SunoloAnelk.setText("");
        FusikoAerio.setText("");
        Sunolo.setText("");

    }//GEN-LAST:event_ClearBtnActionPerformed

    private void KodPolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KodPolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KodPolActionPerformed

    private void Submit4BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Submit4BtnActionPerformed
        PreparedStatement st;
        Connection conn;
        String url = "jdbc:sqlite:C:/Users/BILL/Desktop/polukatoikiadb.db";
        String sql = "INSERT INTO eksodaPolukatoikias (KodPol,MonthYear,Koinoxrista,Thermansi,Sunidioktisia,Anelk) VALUES(?,?,?,?,?,?)";

        try {

            conn = (Connection) DriverManager.getConnection(url);
            st = conn.prepareStatement(sql);
            st.setString(1, KodPol.getText());
            st.setString(2, MonthYear.getText());
            st.setString(3, SunoloKoin.getText());
            st.setString(4,SunoloTher.getText());
            st.setString(5,SunoloSunidioktisia.getText());
            st.setString(6,SunoloAnelk.getText());
            
            st.executeUpdate();

            JOptionPane.showMessageDialog(null, "ΕΠΙΤΥΧΗΣ ΚΑΤΑΧΩΡΗΣΗ!");

        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "AΠΟΤΥΧΗΜΕΝΗ ΚΑΤΑΧΩΡΗΣΗ", "Error", JOptionPane.ERROR_MESSAGE);

        }

    }//GEN-LAST:event_Submit4BtnActionPerformed

    private void SunoloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SunoloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SunoloActionPerformed

    private void SunoloSunidioktisiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SunoloSunidioktisiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SunoloSunidioktisiaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        EisagogiPolukatoikias eispol=new EisagogiPolukatoikias();
        eispol.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
          EisagogiDiamerismatos eisdiamer=new EisagogiDiamerismatos();
          eisdiamer.setVisible(true);
          this.setVisible(false);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
           // 
           JOptionPane.showMessageDialog(null, "ΕΙΣΤΕ ΗΔΗ ΣΕ ΑΥΤΗ ΤΗΝ ΣΕΛΙΔΑ!");
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void CalculateEksodaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CalculateEksodaMouseEntered
    CalculateEksoda.setBackground(new java.awt.Color(0, 0, 51));         // TODO add your handling code here:
    }//GEN-LAST:event_CalculateEksodaMouseEntered

    private void CalculateEksodaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CalculateEksodaMouseExited
CalculateEksoda.setBackground(new java.awt.Color(0, 0, 151));          // TODO add your handling code here:
    }//GEN-LAST:event_CalculateEksodaMouseExited

    private void ClearBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClearBtnMouseEntered
        ClearBtn.setBackground(new java.awt.Color(0, 0, 51));    
    }//GEN-LAST:event_ClearBtnMouseEntered

    private void ClearBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClearBtnMouseExited
        ClearBtn.setBackground(new java.awt.Color(0, 0, 151));  
    }//GEN-LAST:event_ClearBtnMouseExited

    private void Submit4BtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Submit4BtnMouseEntered
        Submit4Btn.setBackground(new java.awt.Color(0, 0, 51)); 
    }//GEN-LAST:event_Submit4BtnMouseEntered

    private void Submit4BtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Submit4BtnMouseExited
         Submit4Btn.setBackground(new java.awt.Color(0, 0, 151)); 
    }//GEN-LAST:event_Submit4BtnMouseExited

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
     EkdosiApodeiksis ekd=new EkdosiApodeiksis();
         ekd.setVisible(true);      
         this.setVisible(false);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        EmfanisiDiamerismatwn emfDiamer=new EmfanisiDiamerismatwn();
        emfDiamer.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EisagogiEksodwnPol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EisagogiEksodwnPol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EisagogiEksodwnPol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EisagogiEksodwnPol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new EisagogiEksodwnPol().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AksiaTherm;
    private javax.swing.JButton CalculateEksoda;
    private javax.swing.JButton ClearBtn;
    private javax.swing.JTextField DiafEksoda;
    private javax.swing.JTextField EksodaAnt;
    private javax.swing.JTextField EksodaPortas;
    private javax.swing.JTextField EksodaTexnikwn;
    private javax.swing.JTextField FusikoAerio;
    private javax.swing.JTextField Katharistria;
    private javax.swing.JTextField KodPol;
    private javax.swing.JTextField MonthYear;
    private javax.swing.JTextField Nero;
    private javax.swing.JLabel Quit1;
    private javax.swing.JTextField Revma;
    private javax.swing.JTextField SintKafstira;
    private javax.swing.JButton Submit4Btn;
    private javax.swing.JTextField Sunolo;
    private javax.swing.JTextField SunoloAnelk;
    private javax.swing.JTextField SunoloKoin;
    private javax.swing.JTextField SunoloSunidioktisia;
    private javax.swing.JTextField SunoloTher;
    private javax.swing.JTextField Suntirisi;
    private javax.swing.JLabel VerifyConn;
    private javax.swing.JTextField Xaratsi;
    private javax.swing.JLabel asdasd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    // End of variables declaration//GEN-END:variables
}
